version: '3.8'

services:
  wireguard:
    image: yurch23/solid-vpn:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 10s
      timeout: 5s
      retries: 3

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wg-dashboard
    depends_on:
      - wireguard
    env_file:
      - .env
    volumes:
      - /etc/wireguard:/etc/wireguard:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - wg-network

networks:
  wg-network:
    driver: bridge
